# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gender Spaces Nottingham
description: >- # this means to ignore newlines until "baseurl:"
  Description would go here
location: Nottingham
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: genderspaces
facebook_username: genderspaces
instagram_username: genderspaces
tumblr_username: genderspaces

permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .travis.yml
  - Rakefile
  - LICENSE
  - CONTRIBUTING.md
  - README.md


collections:
  venues:
    output: true
  events:
    output: true
    permalink: /test/:name/

defaults:
  - scope:
      path: ""
    values:
      noindex: true
  - scope:
      path: ""
      type: venues
    values:
      layout: venue
      permalink: /venue/:name/
  - scope:
      path: ""
      type: events
    values:
      layout: event
      permalink: /event/:name/